export const PRODUCTS = "PRODUCTS";
export const WAREHOUSES = "WAREHOUSES";
export const PRODUCTTYPES = "PRODUCTTYPES";
export const PRODUCTDISCOUNT = "PRODUCTDISCOUNT";
export const PRODUCTINFO = "PRODUCTINFO";
