export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_TYPE = "CREATE_PRODUCT_TYPE";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCT_TYPES_SUCCESS = "LOAD_PRODUCT_TYPES_SUCCESS";
