export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_TYPE = "CREATE_PRODUCT_TYPE";
export const CREATE_WAREHOUSE = "CREATE_WAREHOUSE";
export const CREATE_SALES_INFO = "CREATE_SALES_INFO";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCT_TYPES_SUCCESS = "LOAD_PRODUCT_TYPES_SUCCESS";
export const LOAD_WAREHOUSES_SUCCESS = "LOAD_WAREHOUSES_SUCCESS";
export const LOAD_SALES_INFOS_SUCCESS = "LOAD_SALES_INFOS_SUCCESS";
